// Generated by CoffeeScript 1.6.3
var Filter, flatten, main;

window.requestAnimationFrame = (function() {
  return window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || window.oRequestAnimationFrame || window.msRequestAnimationFrame || function(callback, element) {
    return window.setTimeout(function() {
      return callback();
    }, 1000 / 60);
  };
})();

flatten = function(a) {
  return [].concat.apply([], a);
};

Filter = (function() {
  function Filter(width, height) {
    this.width = width;
    this.height = height;
    this.src = document.createElement('canvas');
    this.src.width = this.width;
    this.src.height = this.height;
    this.src_ctx = this.src.getContext('2d');
    this.dst = document.createElement('canvas');
    this.dst.width = this.width;
    this.dst.height = this.height;
    this.dst_ctx = this.dst.getContext('2d');
  }

  Filter.prototype.setKernel = function(kernel) {
    return this.kernel = kernel;
  };

  Filter.prototype.process = function(image, width, height, cb) {
    var bitmap, i, index, kernel, kernel_radius, kernel_size, offset_px_x, offset_px_y, offset_rgb, result, sliced, v, x, y, _i, _j, _k, _l, _ref, _ref1, _ref2;
    this.clear();
    this.src_ctx.drawImage(image, 0, 0, width, height, 0, 0, this.width, this.height);
    this.dst_ctx.drawImage(image, 0, 0, width, height, 0, 0, this.width, this.height);
    bitmap = this.src_ctx.getImageData(0, 0, this.width, this.height);
    result = this.src_ctx.createImageData(this.width, this.height);
    kernel_size = this.kernel[0].length;
    kernel_radius = this.kernel[0].length - 1 / 2;
    kernel = flatten(this.kernel);
    for (y = _i = 20, _ref = this.height - 2; 20 <= _ref ? _i <= _ref : _i >= _ref; y = 20 <= _ref ? ++_i : --_i) {
      offset_px_y = y * this.width;
      for (x = _j = 20, _ref1 = this.width - 2; 20 <= _ref1 ? _j <= _ref1 : _j >= _ref1; x = 20 <= _ref1 ? ++_j : --_j) {
        offset_px_x = x;
        sliced = this.src_ctx.getImageData(x - kernel_radius, y - kernel_radius, kernel_size, kernel_size).data;
        index = (offset_px_y + offset_px_x) * 4;
        for (offset_rgb = _k = 0; _k <= 2; offset_rgb = ++_k) {
          v = 0;
          for (i = _l = 0, _ref2 = kernel.length - 1; 0 <= _ref2 ? _l <= _ref2 : _l >= _ref2; i = 0 <= _ref2 ? ++_l : --_l) {
            v += sliced[i * 4 + offset_rgb] * kernel[i];
          }
          if (v > 255) {
            v = 255;
          }
          if (v < 0) {
            v = 0;
          }
          result.data[index + offset_rgb] = v;
        }
        result.data[index + 3] = 255;
      }
    }
    this.src_ctx.putImageData(result, 0, 0);
    return cb(this.src.toDataURL());
  };

  Filter.prototype.clear = function() {
    var ctx, _i, _len, _ref, _results;
    _ref = [this.src_ctx, this.dst_ctx];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      ctx = _ref[_i];
      _results.push(ctx.clearRect(0, 0, this.width, this.height));
    }
    return _results;
  };

  return Filter;

})();

main = function() {
  var animationLoop, error, filter, img, process, success, video;
  video = document.querySelector('#video');
  img = document.querySelector('#screen');
  filter = null;
  process = function() {
    var scale;
    if (!video.videoWidth) {
      return;
    }
    if (!filter) {
      scale = 0.25;
      filter = new Filter(video.videoWidth * scale, video.videoHeight * scale);
      filter.setKernel([[-2, -1, 0], [-1, 1, 1], [0, 1, 2]]);
      filter.setKernel([[-1, 0, 1], [-1, 0, 1], [-1, 0, 1]]);
      filter.setKernel([[-1, -1, -1], [0, 0, 0], [1, 1, 1]]);
    }
    return filter.process(video, video.videoWidth, video.videoHeight, function(url) {
      return img.src = url;
    });
  };
  success = function(stream) {
    video = document.querySelector('#video');
    video.src = window.URL.createObjectURL(stream);
    return video.play();
  };
  error = function() {
    return alert('error');
  };
  navigator.webkitGetUserMedia({
    video: true
  }, success, error);
  animationLoop = function() {
    process();
    return setTimeout(animationLoop, 100);
  };
  return animationLoop();
};

main();
