# http://nonn-et-twk.net/twk/google-app-engine-html
application: hitode909-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: no

skip_files:
- ^(node_modules/.*)
- ^(.git/.*)

handlers:

- url: /dic/js/(.*)
  static_files: dic/public/js/\1
  upload: dic/public/js/(.*)

- url: /dic/image/(.*)
  static_files: dic/public/image/\1
  upload: dic/public/image/(.*)

- url: /dic/css/(.*)
  static_files: dic/public/css/\1
  upload: dic/public/css/(.*)

- url: /dic/.*
  script: dic/dic.py

- url: /glitch/api.*
  script: glitch/glitch.py

- url: /proxy/.*
  script: proxy/proxy.py

- url: /thumbnail.to/
  static_files: htdocs/thumbnail.to/index.html
  upload: htdocs/thumbnail.to/index.html

- url: /thumbnail.to/.*
  script: thumbnail.to/thumb.py

- url: /tinyurl/
  script: tinyurl/main.py

- url: /png/.*
  script: png/main.py

- url: /text/.*
  script: text/main.py

- url: /blogparts/.*
  script: blogparts/main.py

- url: /album/.*
  script: album/album.py

- url: /color/.+
  script: color/color.py

- url: /oauth/.*
  script: oauth/oauth_handler.py

- url: /tweet/.*
  script: tweet/tweet.py

- url: /public_list/.+
  script: public_list/public_list.py

- url: /slitscan/
  static_files: htdocs/slitscan/index.html
  upload: htdocs/slitscan/index.html
  secure: always

- url: (.*)/
  static_files: htdocs\1/index.html
  upload: htdocs(.*)/index.html

- url: /sentence_imager/-/.*
  static_files: htdocs/sentence_imager/index.html
  upload: public/sentence_imager/index.html


- url: /(.*\.py)
  script: \1

- url: /favicon.ico
  static_files: htdocs/favicon.ico
  upload: htdocs/favicon.ico
  mime_type: image/x-icon

- url: /html909/TR909all/(.*)
  static_files: htdocs/html909/TR909all/\1
  upload: htdocs/html909/TR909all/(.*)
  mime_type: audio/x-wav

- url: /(.*)
  static_files: htdocs/\1
  upload: htdocs/(.*)
