# http://nonn-et-twk.net/twk/google-app-engine-html
application: hitode909
version: 1
runtime: python
api_version: 1

handlers:

- url: /dic/js/(.*)
  static_files: dic/public/js/\1
  upload: dic/public/js/(.*)  

- url: /dic/image/(.*)
  static_files: dic/public/image/\1
  upload: dic/public/image/(.*)  

- url: /dic/css/(.*)
  static_files: dic/public/css/\1
  upload: dic/public/css/(.*)  

- url: /dic/.*
  script: dic/dic.py

- url: /glitch/api.*
  script: glitch/glitch.py

- url: /proxy/.*
  script: proxy/proxy.py

- url: /tinyurl/
  script: tinyurl/main.py

- url: /png/.*
  script: png/main.py

- url: /blogparts/.*
  script: blogparts/main.py

- url: /album/.*
  script: album/album.py

- url: /color/.+
  script: color/color.py

- url: /public_list/.+
  script: public_list/public_list.py

- url: (.*)/
  static_files: htdocs\1/index.html
  upload: htdocs(.*)/index.html

- url: /(.*\.py)
  script: \1

- url: /favicon.ico
  static_files: htdocs/favicon.ico
  upload: htdocs/favicon.ico
  mime_type: image/x-icon

- url: /(.*)
  static_files: htdocs/\1
  upload: htdocs/(.*)
